### ISSUE TITLE
División de las ramas para el backend Gestionar Servicio y Administrador

### ISSUE THREAD

**Issue by cdelriot1121** [cdelriot1121/Spring.ClassroomProject-SERVIAPP#2]
### **Hola que tal abro un nuevo Asunto para la división del trabajo**

Personas convocadas: @Gaos-Orozco @valeriahh33 @Sirwillys06 @cdelriot1121 

He generado dos branches para poder dividir el desarrollo del backend de una forma mas segura, para nuevas ramas generadas que son `backend-gest.serv` y `backend-admin` que provienen de nuestra rama `main`. 

Entonces, la rama `backend-gest.serv` lo podemos tomar para desarrollar las funcionalidad del usuario, modificando las clases controlador, entitys, y services, que van a intervenir en este apartado. Y yo, a la par estaré en la rama `backend-admin`, integrando las mismas clases controlador, services, etc. Para el apartado de las funcionalidades del administrador.

Como mencione anteriormente a lo largo de la semana me encargare de hacer, las funciones iniciales del apartado administrador de la plataforma (función delegada a: @cdelriot1121 )

**Comment by Sirwillys06** [comment]
ok

**Comment by cdelriot1121** [comment]
Perdona por no avisar a tiempo, la rama con nombre `backend-gest.serv` se ha cambiado a `backend-usuario`. Lo puedes visualizar en las ramas del repositorio
